name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    
permissions:
  contents: write
  
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '9.0.100'

      - name: Test 
        run: dotnet test --verbosity diagnostic
        
      - name: Publish .NET Core Project
        run: dotnet publish PortfolioStalker.sln -c Release -o release --nologo

      - name: Change base-tag in index.html from / to testpages
        run: sed -i 's/<base href="\/" \/>/<base href="\/portfoliostalker\/" \/>/g' release/wwwroot/index.html

      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
  
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
